from .backgroundWidget import BackgroundWidget
from .signalWidget import SignalWidget
from .displayedEpochWidget import DisplayedEpochWidget
from .spectogramWidget import SpectogramWidget
from .hypnogramWidget import HypnogramWidget
from .spectogramSlider import SpectogramSlider
from .hypnogramSlider import HypnogramSlider
from .paintEventWidget import PaintEventWidget
from .rectanglePower import RectanglePower
from .annotationContainer import AnnotationContainer
from .configurationWindow import ConfigurationWindow
